### ISSUE TITLE
Adding new commands

### ISSUE THREAD

**Issue by IceRoG** [ulich/esphome-vaillant-x6#1]
Hi ulich,
i wanted to ask how to add new commands to this.
I forked it and tried it by i only get an error with invalid response and nothing works.
Your version works for the values you provided.
Thank you!

**Comment by IceRoG** [comment]
And while i'm here... Is there a possibility to set the values through the X6-Port?
For example to change the Setpoint Temperature and to heat the water on demand?
Or is this only possible through the 7-8-9 Port?

**Comment by ulich** [comment]
To add another command, just add another block similar to the ones defined here https://github.com/ulich/esphome-vaillant-x6/blob/main/components/vaillant_x6/vaillant_x6.cpp in lines 17-81.

The things you have to be careful with:
- The type of command depending on the type of response you expect (GetOnOffStatusCommand, GetTemperatureCommand)
- The expected response length (given in the constructor to the Command)
- The request bytes, including the checksum as described here: https://old.ethersex.de/index.php/Vaillant_X6_Schnittstelle

There should be another log message (on debug level) explaining the reason why the response is invalid (from [here](https://github.com/ulich/esphome-vaillant-x6/blob/b281bfe0f840012f20df4f181005db0f1fafb407/components/vaillant_x6/vaillant_x6.cpp#L128) and [here](https://github.com/ulich/esphome-vaillant-x6/blob/b281bfe0f840012f20df4f181005db0f1fafb407/components/vaillant_x6/vaillant_x6.cpp#L134)).

Which command(s) are you trying to add? You can also open a PR with the code you have and I can take a look.

**Comment by ulich** [comment]
> And while i'm here... Is there a possibility to set the values through the X6-Port? For example to change the Setpoint Temperature and to heat the water on demand? Or is this only possible through the 7-8-9 Port?

I have never tried. According to https://old.ethersex.de/index.php/Vaillant_X6_Schnittstelle this seems to be possible from the protocol (2nd byte is 0x80) but I’m not sure what to send exactly. 

If you have an idea, I can try to add this.

**Comment by ulich** [comment]
By the way, you seem to be the second person who wants to add more commands. We can use this issue to collect the commands that are wanted so I can implement them. I will also think about making it configurable from the esphome yaml file.

**Comment by IceRoG** [comment]
It seems as though my boiler did not support the command I send, which is why it send errors.
So i think just adding the command manually if needed should be possible.

**Comment by IceRoG** [comment]
If time allows I will try to play with the send commands and see if I can get something to work. Otherwise there is always the option to utilize the 7-8-9 Port to emulate a thermostat.
As far as I understand this should allow the ESP to "request" that warm water is made.

**Comment by ulich** [comment]
Custom sensors can now be added without forking: https://github.com/ulich/esphome-vaillant-x6/commit/781f92e47106d1d86548ef54c00a162b748f31ac

I'm still happy to add built-in sensors for any sensors that are valuable but are missing.

**Comment by ulich** [comment]
@krutzke I saw your fork. You should be able to leverage the above mentioned change and add your own custom sensors now, without having to fork the project. I can probably also add your sensors to the list of built-in sensors.

**Comment by krutzke** [comment]
@ulich I've just seen it. Looks great. I'll try it out in the next few days.

**Comment by krutzke** [comment]
It work for me!
I also need these 2 sensors. The integration via the sonsor parameters is fine for me.

```
  sensors:
    - id: vaillant_x6_hot_water_temperature
      name: Vaillant X6 Hot Water Temperature
      icon: mdi:thermometer-water
      unit_of_measurement: °C
      accuracy_decimals: 1
      device_class: temperature
      response_type: AnalogueValue2Bytes
      command_byte: 0x16
      response_length: 3
      poll_interval: 30

    - id: vaillant_x6_hot_water_target_temperature
      name: Vaillant X6 Hot Water Target Temperature
      icon: mdi:thermometer-water
      unit_of_measurement: °C
      accuracy_decimals: 1
      device_class: temperature
      response_type: AnalogueValue2Bytes
      command_byte: 0x01
      response_length: 2
      poll_interval: 60
```
